name: Heroku deploy

on: [push, pull_request]

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - "server/*"
#       - "server/*/*"
#       - "server/*/*/*"
#       - "server/*/*/*/*"
#       - "server/*/*/*/*/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install heroku cli
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Setup heroku auth
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "machine git.heroku.com\n  login arjunattam@gmail.com\n  password $HEROKU_API_KEY" > ~/.netrc
      - name: Verify repo
        run: ls -alh
      - name: Setup heroku remote
        run: git remote add heroku https://git.heroku.com/toilet-paper-app.git
      - name: Push to heroku
        run: git subtree push --prefix server heroku master
